#!/usr/bin/env python3
"""Generate tables.rox (Doom state machine + mobj info as Roxal parallel lists)
from the GPL linuxdoom-1.10 sources. Run offline; the generated tables.rox is
committed so the game stays pure Roxal at runtime.

Usage: gen_tables.py <path-to-linuxdoom-1.10-dir-with-info.c/info.h/p_mobj.h>
"""
import re
import sys
import os

src = sys.argv[1] if len(sys.argv) > 1 else '.'
info_c = open(os.path.join(src, 'info.c')).read()
info_h = open(os.path.join(src, 'info.h')).read()
p_mobj_h = open(os.path.join(src, 'p_mobj.h')).read()


def parse_enum(text, first_name):
    """Return name->index for a C enum starting at first_name (no explicit values)."""
    start = text.index(first_name)
    end = text.index('}', start)
    names = re.findall(r'\b([A-Z][A-Z0-9_]+)\b', text[start:end])
    out = {}
    i = 0
    for n in names:
        if n.startswith('NUM'):
            continue
        if n not in out:
            out[n] = i
            i += 1
    return out


sprites = parse_enum(info_h, 'SPR_TROO')
states_e = parse_enum(info_h, 'S_NULL')
mobjs_e = parse_enum(info_h, 'MT_PLAYER')

# MF_* flag values (explicit hex/decimal assignments in p_mobj.h)
mf = {}
for m in re.finditer(r'(MF_[A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|\d+)', p_mobj_h):
    mf[m.group(1)] = int(m.group(2), 0)

# sprite names
m = re.search(r'sprnames\[NUMSPRITES\]\s*=\s*\{(.*?)\};', info_c, re.S)
sprnames = re.findall(r'"([A-Z0-9]{4})"', m.group(1))

# states[]: {SPR_X, frame, tics, {action}, S_NEXT, misc1, misc2}
m = re.search(r'states\[NUMSTATES\]\s*=\s*\{(.*?)\n\};', info_c, re.S)
rows = re.findall(
    r'\{\s*(SPR_[A-Z0-9_]+)\s*,\s*([0-9|]+)\s*,\s*(-?\d+)\s*,\s*\{\s*(NULL|A_[A-Za-z0-9_]+)\s*\}\s*,\s*(S_[A-Z0-9_]+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*\}',
    m.group(1))
st_spr, st_frm, st_tics, st_act, st_next = [], [], [], [], []
for spr, frm, tics, act, nxt, m1, m2 in rows:
    st_spr.append(sprites[spr])
    st_frm.append(int(frm))
    st_tics.append(int(tics))
    st_act.append('' if act == 'NULL' else act)
    st_next.append(states_e[nxt])

# mobjinfo[]: value lines annotated with field-name comments
m = re.search(r'mobjinfo\[NUMMOBJTYPES\]\s*=\s*\{(.*)\n\};', info_c, re.S)
blocks = re.findall(r'\{\s*//\s*(MT_[A-Z0-9_]+)(.*?)\n\s*\},?', m.group(1), re.S)
FIELDS = ['doomednum', 'spawnstate', 'spawnhealth', 'seestate', 'reactiontime',
          'painstate', 'painchance', 'meleestate', 'missilestate', 'deathstate',
          'xdeathstate', 'speed', 'radius', 'height', 'mass', 'damage',
          'flags', 'raisestate']


def val_of(expr):
    expr = expr.strip()
    if expr.startswith('S_'):
        return states_e[expr]
    if expr.startswith('sfx_'):
        return 0
    if '|' in expr:
        v = 0
        for part in expr.split('|'):
            v |= mf[part.strip()]
        return v
    if expr.startswith('MF_'):
        return mf[expr]
    if 'FRACUNIT' in expr:
        n = expr.replace('*FRACUNIT', '').strip()
        return int(n)
    return int(expr)


mi = {f: [] for f in FIELDS}
mi_names = []
for name, body in blocks:
    mi_names.append(name)
    fields = {}
    for vm in re.finditer(r'([^\s,][^,]*?)\s*,?\s*//\s*([a-z0-9]+)', body):
        fields[vm.group(2)] = vm.group(1)
    for f in FIELDS:
        mi[f].append(val_of(fields[f]) if f in fields else 0)


def fmt_list(name, vals, quote=False):
    # Roxal caps list literals at 255 elements: chunked extends
    if quote:
        items = ["'" + v + "'" for v in vals]
    else:
        items = [str(v) for v in vals]
    lines = ['var ' + name + ' = []']
    for c0 in range(0, len(items), 200):
        chunk = items[c0:c0 + 200]
        cur = name + '.extend(['
        for it in chunk:
            if len(cur) + len(it) + 2 > 100:
                lines.append(cur)
                cur = '  '
            cur += it + ','
        lines.append(cur.rstrip(',') + '])')
    return '\n'.join(lines)


out = ['# GENERATED by gen_tables.py from linuxdoom-1.10 info.c/info.h/p_mobj.h',
       '# (GPL2). Do not edit by hand — rerun the generator.',
       '']
out.append(fmt_list('SPRNAMES', sprnames, quote=True))
out.append(fmt_list('ST_SPR', st_spr))
out.append(fmt_list('ST_FRM', st_frm))
out.append(fmt_list('ST_TICS', st_tics))
out.append(fmt_list('ST_ACT', st_act, quote=True))
out.append(fmt_list('ST_NEXT', st_next))
out.append(fmt_list('MI_NAMES', mi_names, quote=True))
out.append(fmt_list('MI_ED', mi['doomednum']))
out.append(fmt_list('MI_SPAWN', mi['spawnstate']))
out.append(fmt_list('MI_HEALTH', mi['spawnhealth']))
out.append(fmt_list('MI_SEE', mi['seestate']))
out.append(fmt_list('MI_REACT', mi['reactiontime']))
out.append(fmt_list('MI_PAIN', mi['painstate']))
out.append(fmt_list('MI_PAINCH', mi['painchance']))
out.append(fmt_list('MI_MELEE', mi['meleestate']))
out.append(fmt_list('MI_MISSILE', mi['missilestate']))
out.append(fmt_list('MI_DEATH', mi['deathstate']))
out.append(fmt_list('MI_XDEATH', mi['xdeathstate']))
out.append(fmt_list('MI_SPEED', mi['speed']))
out.append(fmt_list('MI_RADIUS', mi['radius']))
out.append(fmt_list('MI_HEIGHT', mi['height']))
out.append(fmt_list('MI_MASS', mi['mass']))
out.append(fmt_list('MI_DAMAGE', mi['damage']))
out.append(fmt_list('MI_FLAGS', mi['flags']))

# the deterministic P_Random table (m_random.c)
mr = open(os.path.join(src, 'm_random.c')).read()
rm = re.search(r'rndtable\[256\]\s*=\s*\{(.*?)\};', mr, re.S)
rnd = [int(v) for v in re.findall(r'\d+', rm.group(1))]
assert len(rnd) == 256
out.append(fmt_list('RNDTABLE', rnd))

# mobj flag constants the game logic needs
for f in ['MF_SPECIAL', 'MF_SOLID', 'MF_SHOOTABLE', 'MF_NOBLOCKMAP', 'MF_AMBUSH',
          'MF_MISSILE', 'MF_NOGRAVITY', 'MF_SPAWNCEILING', 'MF_COUNTKILL', 'MF_NOSECTOR']:
    out.append(f'var {f} = {mf[f]}')
out.append('')

dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'tables.rox')
open(dst, 'w').write('\n'.join(out) + '\n')
print(f'wrote {dst}: {len(sprnames)} sprites, {len(st_spr)} states, {len(mi_names)} mobj types')
