import { useEffect, useMemo, useRef, useState } from 'react';
import { startRoxal, runScript, scriptParked, ensureServices, stopCurrent } from './roxal.js';
import { warmNnProvider } from './nn-provider.js';
import { hostUrlFromLocation } from './lib/host.js';
import Editor, { disposeModel } from './Editor.jsx';
import TanksPanel from './TanksPanel.jsx';
import MnistPanel from './MnistPanel.jsx';
import { lazy, Suspense } from 'react';
const Tanks3D = lazy(() => import('./Tanks3D.jsx'));
// Lazy like Tanks3D: React Flow only loads for users who open a diagram.
const DfEditor = lazy(() => import('./DfEditor.jsx'));
import { isDiagramSource, dfCall } from './dfdoc.js';
import { armDebugSession, DebugStoreAdapter } from './debug.js';
import { useRoxal, useRoxalStore } from './roxal-react.js';
import FileMenu from './lib/FileMenu.jsx';
import Repl from './lib/Repl.jsx';
// The demos are PLAIN .rox files -- editable in any editor, with Roxal syntax
// rather than a JavaScript string. Vite's ?raw suffix hands us their text; the
// IDE seeds them into /data on a first visit, after which they are ordinary
// files the user owns.
import TANKS_SRC from './demos/tanks.rox?raw';
import OVEN_SRC from './demos/oven.rox?raw';
import MNIST_SRC from './demos/mnist.rox?raw';
import COSINE_SRC from './demos/cosine.rox?raw';
import FLIPFLOP_SRC from './demos/flipflop.rox?raw';
import COUNTER4_SRC from './demos/counter4.rox?raw';

// The examples the IDE seeds on a first visit. All are ordinary files
// afterwards: edit, save, re-run, or open another from the File menu.
// tanks.rox opens first for a visitor with no history -- it is the one that
// shows what a signal network looks like at a glance. mnist.rox is a batch
// script (prints and ends) demonstrating in-browser ai.nn inference.
// cosine.rox is a data-flow DIAGRAM file (dfdoc dialect, generated by
// modules/dfdoc.rox) -- it opens as a canvas, not as text.
const EXAMPLES = { 'tanks.rox': TANKS_SRC, 'oven.rox': OVEN_SRC, 'mnist.rox': MNIST_SRC,
                   'cosine.rox': COSINE_SRC, 'flipflop.rox': FLIPFLOP_SRC,
                   'counter4.rox': COUNTER4_SRC };
// Which panel the app pane shows is decided by WHICH STORE the running script
// exposed -- and by generation, not mere presence, because the JS registry
// keeps a stale record for every store any previous run exposed.
const PANELS = ['tanks', 'oven', 'digit'];
const pickPanel = rox =>
    PANELS.map(n => ({ n, g: rox.roxalStoreGeneration?.(n) ?? 0 }))
          .filter(x => x.g > 0)
          .sort((a, b) => b.g - a.g)[0]?.n ?? null;

// Files live in the host's data directory: /data in the wasm FS, which the
// host backs with OPFS in the browser (they survive a reload), or the --root
// directory of a native `roxal --web-host`. The IDE reaches them through the
// "workspace" store (a Roxal actor in the web module using fileio itself), so
// File > Open here exercises the same API user scripts get. The bootstrap's
// build store reports which directory this host uses.
let dataDir = '/data';
// The bootstrap also publishes what this build of the VM can do. `features` is
// a sys constant (sys.* is implicit), so the header reports the real compiled
// feature set rather than a list maintained by hand over here -- which would
// go stale the first time a module is enabled or dropped.
const BOOTSTRAP = [
    'import web',
    'type Build object:',
    '  var platform :string = platform',
    '  var version :string = version',
    '  var features = features',
    '  var data_dir :string = host_dir("data")',
    'web.expose("build", Build())',
    'web.serve()',
    '',
].join('\n');
const LAST_FILE_KEY = 'roxal-ide-last-file';

// The file named by ?file=, normalised to the bare name fs_list reports:
// `counter4`, `counter4.rox` and `/data/counter4.rox` all name the same file,
// and a link is more likely to be typed by hand than any other entry point.
// Returns null when the parameter is absent or empty.
function requestedFile() {
    const raw = (new URLSearchParams(location.search).get('file') || '').trim();
    if (!raw) return null;
    const name = raw.replace(/^.*\//, '');          // tolerate a leading path
    return name.endsWith('.rox') ? name : name + '.rox';
}
const SEED_STAMP_KEY = 'roxal-ide-seeded';

// FNV-1a, enough to answer "is this byte-for-byte what we wrote?" -- the only
// question asked of it. Storing the full text would work too and cost 8KB of
// localStorage per deploy's worth of examples.
function hash(text) {
    let h = 0x811c9dc5;
    for (let i = 0; i < text.length; i++) {
        h ^= text.charCodeAt(i);
        h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h.toString(36);
}
// Copies we shipped in an earlier deploy, by hash. A visitor from before the
// stamping above has no record, so a pristine old copy is indistinguishable
// from an edited one -- except when it matches a version we know we wrote.
// Add the outgoing hash here whenever an example changes.
const KNOWN_PRIOR = {
    'mnist.rox': ['11ljg1w'],   // the print-and-exit version, pre drawing panel
    'counter4.rox': ['q916um',  // pre 'value' packed-int output
                     '13p2wv2'], // 'value' but pre probe=true selection
};
// The in-app escape hatch for stale-origin trouble: everything a page may
// clear about its own origin -- service workers (whose header-injection
// fetch path can outlive deploys), CacheStorage, OPFS files, localStorage,
// IndexedDB -- then a reload to refetch entry files. The HTTP cache is not
// directly clearable, but with the worker gone a reload revalidates.
// Every step is best-effort: a locked OPFS file (the running VM may hold
// handles) must not stop the rest.
async function resetSiteData() {
    try {
        const regs = await navigator.serviceWorker?.getRegistrations?.() ?? [];
        await Promise.all(regs.map(r => r.unregister().catch(() => {})));
    } catch { /* no SW support */ }
    try {
        const keys = await window.caches?.keys?.() ?? [];
        await Promise.all(keys.map(k => window.caches.delete(k).catch(() => {})));
    } catch { /* no CacheStorage */ }
    try {
        const root = await navigator.storage?.getDirectory?.();
        if (root) {
            for await (const name of root.keys())
                await root.removeEntry(name, { recursive: true }).catch(() => {});
        }
    } catch { /* no OPFS */ }
    try { localStorage.clear(); } catch { /* private mode */ }
    try {
        const dbs = await window.indexedDB?.databases?.() ?? [];
        await Promise.all(dbs.map(d => d.name && window.indexedDB.deleteDatabase(d.name)));
    } catch { /* databases() is Chromium-only */ }
    window.location.reload();
}

const readStamps = () => {
    try { return JSON.parse(localStorage.getItem(SEED_STAMP_KEY) || '{}'); }
    catch { return {}; }
};
const writeStamps = s => {
    try { localStorage.setItem(SEED_STAMP_KEY, JSON.stringify(s)); } catch { /* private mode */ }
};
const SOURCE_OPEN_KEY = 'roxal-ide-source-open';
const TANKS_VIEW_KEY = 'roxal-ide-tanks-view';

// Everything below is ordinary React. The only Roxal-aware lines are the two
// hooks -- useRoxal for state, useRoxalStore for actions. No effects to wire, no
// polling, no message plumbing: the store is an external store and React already
// knows how to consume one.
// What this build of the VM actually has compiled in, straight from the sys
// constant. The wasm build is a different feature set from the native one --
// no sockets or FFI, but regex, xml, media images and ai.nn -- and that is
// worth stating on the page rather than leaving a visitor to guess why an
// import failed.
function BuildInfo({ rox }) {
    const build = useRoxal(rox, 'build');
    const features = Array.isArray(build.features) ? build.features : null;
    if (!features) return null;
    return (
        <p className="build-info">
            <span className="build-label">this build:</span>
            {features.map(f => <code key={f} className="feature">{f}</code>)}
            <span className="build-label">
                on {build.platform} — roxal {build.version}
            </span>
        </p>
    );
}

function OvenPanel({ rox }) {
    const oven = useRoxal(rox, 'oven');
    const store = useRoxalStore(rox, 'oven');

    if (oven.temperature === undefined)
        return <p className="loading">this app exposes no "oven" store — watch the output pane</p>;

    return (
        <div className="panel">
            <div className="readout">
                <Field label="temperature" value={fmt(oven.temperature, 1) + '°'} big />
                <Field label="setpoint" value={fmt(oven.setpoint, 0) + '°'} />
                <Field label="error" value={fmt(oven.error, 1)} />
                <Field label="heater" value={oven.heating ? 'ON' : 'off'}
                       tone={oven.heating ? 'busy' : 'calm'} />
            </div>

            <Track position={(oven.temperature ?? 0) / 3} target={(oven.setpoint ?? 0) / 3} />
            <Duty value={oven.duty ?? 0} />

            <label className="slider">
                <span>setpoint</span>
                {/* Writes straight into the Roxal signal -- the network picks it up. */}
                <input type="range" min="20" max="260" step="5"
                       value={oven.setpoint ?? 20}
                       onChange={e => store.set('setpoint', Number(e.target.value))} />
                <b>{fmt(oven.setpoint, 0)}°</b>
            </label>

            <div className="actions">
                <button onClick={() => store.call('preheat')}>preheat 150°</button>
                <button onClick={() => store.call('reflow')}>reflow 240°</button>
                <button onClick={() => store.call('cool')}>cool</button>
            </div>

            <p className="log">{oven.phase}</p>
        </div>
    );
}

const fmt = (v, places) => (typeof v === 'number' ? v.toFixed(places) : '–');

function Field({ label, value, big, tone }) {
    return (
        <div className="field">
            <span className="k">{label}</span>
            <span className={'v' + (big ? ' big' : '') + (tone ? ' ' + tone : '')}>
                {value ?? '–'}
            </span>
        </div>
    );
}

// The lifted duty_for() node, rendered as a bar.
function Duty({ value }) {
    return (
        <div className="duty">
            <span className="k">duty</span>
            <div className="duty-track">
                <div className="duty-fill" style={{ width: Math.round(value * 100) + '%' }} />
            </div>
        </div>
    );
}

// A view that only makes sense because temperature arrives at a steady 20 Hz.
function Track({ position, target }) {
    const pct = v => Math.max(0, Math.min(100, v));
    return (
        <div className="track">
            <div className="track-target" style={{ left: pct(target) + '%' }} />
            <div className="track-pos" style={{ left: pct(position) + '%' }} />
        </div>
    );
}

export default function App() {
    const [rox, setRox] = useState(null);
    // The VM, reachable from code whose closure predates it.  Boot is one
    // long async function started on the FIRST render, so every helper it
    // calls sees the `rox` of that render -- null -- however far into the
    // boot the call happens.  Set alongside the state, never after it.
    const roxRef = useRef(null);
    const [error, setError] = useState(null);
    const [output, setOutput] = useState('');
    const [running, setRunning] = useState(false);
    const [runError, setRunError] = useState(null);
    // A finished batch script is not a failure -- it just has no live app.
    const [runBenign, setRunBenign] = useState(false);

    // --- debugger (demo integration) ----------------------------------------
    const [debugOn, setDebugOn] = useState(false);
    const [bps, setBps] = useState({});          // file -> [lines]
    // Mirror of `bps` for the run path.  A run is started from a closure
    // captured when it was REQUESTED, but its pre-run breakpoint push
    // happens seconds later, after the old program has been displaced --
    // and set_breakpoints REPLACES the whole set for a source, so pushing
    // a stale snapshot silently erases every breakpoint set in between.
    const bpsRef = useRef({});
    const [dbgStop, setDbgStop] = useState(null);        // last stop state()
    const [dbgInfo, setDbgInfo] = useState(null);        // {frames, vars}
    const [dbgLive, setDbgLive] = useState(false);       // the session store answers
    const dbgAdapter = useMemo(() => (rox ? new DebugStoreAdapter(rox) : null), [rox]);
    const dbgStopKeyRef = useRef('');
    // Mirror of dbgStop for the run path (closures there are older than
    // the state they need to read).
    const dbgStopRef = useRef(null);
    const debugOnRef = useRef(false);
    debugOnRef.current = debugOn;

    // Workspace state. Monaco models are the source of truth for content; this
    // component tracks which files exist, which are open, and which is active.
    const [files, setFiles] = useState([]);          // names in /data
    const [tabs, setTabs] = useState([]);            // open file names
    const [active, setActive] = useState(null);      // active file name
    const [seed, setSeed] = useState({});            // name -> initial content
    const [dirtyTabs, setDirtyTabs] = useState({});  // name -> bool

    // Stable store handles (roxalStore returns a fresh object per call).
    const ide = useMemo(() => (rox ? rox.roxalStore('ide') : null), [rox]);
    const workspace = useMemo(() => (rox ? rox.roxalStore('workspace') : null), [rox]);
    const df = useMemo(() => (rox ? rox.roxalStore('df') : null), [rox]);
    // Per-file diagram/source choice. A diagram file opens as its canvas; the
    // source view is editable, and toggling back re-opens the buffer into the
    // canvas -- out-of-dialect edits get a refusal banner there, never mangled.
    const [viewModes, setViewModes] = useState({});
    // Remount the panel after a re-run so hooks re-read the replaced store.
    const [generation, setGeneration] = useState(0);
    const [panel, setPanel] = useState(null);
    // Collapsing the source pane hands the whole width to the running app --
    // which is what a demo wants, and what a small screen needs. Remembered,
    // because a preference that resets every reload is not a preference.
    const [sourceOpen, setSourceOpen] = useState(
        () => localStorage.getItem(SOURCE_OPEN_KEY) !== 'false');
    const toggleSource = () => setSourceOpen(v => {
        localStorage.setItem(SOURCE_OPEN_KEY, String(!v));
        return !v;
    });
    // 2D or 3D for the tanks app -- same store either way; tanks.rox does not
    // know which view it has, which is rather the point.
    const [tanksView, setTanksView] = useState(
        () => localStorage.getItem(TANKS_VIEW_KEY) || '3d');
    const pickView = v => { localStorage.setItem(TANKS_VIEW_KEY, v); setTanksView(v); };
    // Pauses the RENDERER, not the app: the network keeps running (it is the
    // thing being demonstrated, and it is cheap); the WebGL loop is what spins
    // a CPU/GPU. Deliberately not persisted -- a fresh page should play.
    const [paused, setPaused] = useState(false);
    // Output length marker for REPL capture.
    const outputRef = useRef('');
    // Deliberately exposed, like window.monaco: browser tests and console
    // debugging reach stores through it instead of simulating UI.
    useEffect(() => { roxRef.current = rox; window.__rox = rox; }, [rox]);
    // 'clear' hides everything before the mark -- the VM-side buffer only
    // grows, so clearing is a display offset, not a truncation.
    const [outputClearAt, setOutputClearAt] = useState(0);
    // Terminal-style scroll: follow new output unless the user scrolled up
    // to read; follow again once they return to the bottom.
    const outPaneRef = useRef(null);
    const outPinnedRef = useRef(true);
    useEffect(() => {
        const el = outPaneRef.current;
        if (el && outPinnedRef.current) el.scrollTop = el.scrollHeight;
    }, [output, outputClearAt]);
    const [replGen, setReplGen] = useState(0);
    // Debounced autosave for diagram (canvas) edits.
    const autosaveRef = useRef(null);
    useEffect(() => () => clearTimeout(autosaveRef.current), []);
    // True while THIS component is deliberately stopping/starting a script, so
    // the liveness watchdog does not re-park its own bootstrap underneath a
    // restart already in progress -- two recoveries racing leaves the second
    // one queued behind the first one's parked script, i.e. never running.
    const busyRef = useRef(false);
    // Runs are serialized AND supersedable.  Starting a run is a sequence of
    // waits (displace the old program, restore services, wait for the new one
    // to expose its store) that lasts up to 20s for a batch script, which
    // never exposes anything.  Anything the user asks for during that window
    // -- press Run again, switch debugging on -- must displace the pending
    // run, not be dropped because "a run is in progress": each request takes
    // a sequence number, the superseded one bails at its next wait point, and
    // the new one begins only once it has unwound.
    const runSeqRef = useRef(0);
    const runChainRef = useRef(Promise.resolve());

    const filePath = name => dataDir + '/' + name;
    const modelText = name => {
        const monaco = window.monaco;
        const m = monaco?.editor.getModel(monaco.Uri.parse('inmemory://roxal' + filePath(name)));
        return m ? m.getValue() : (seed[name] ?? '');
    };
    // The canvas pushes each op's regenerated source here; writing through the
    // model keeps dirty-tracking and Save on their existing paths.
    const writeModel = (name, src) => {
        const monaco = window.monaco;
        const m = monaco?.editor.getModel(monaco.Uri.parse('inmemory://roxal' + filePath(name)));
        if (m) { if (m.getValue() !== src) m.setValue(src); }
        else setSeed(s => (s[name] === src ? s : { ...s, [name]: src }));
    };
    const activeIsDiagram = active != null && isDiagramSource(modelText(active));
    const activeView = activeIsDiagram ? (viewModes[active] ?? 'diagram') : 'source';

    async function refreshFiles(ws) {
        const list = await ws.call('fs_list', dataDir);
        // only .rox sources: running a /data script leaves a compiled .roc
        // cache beside it, which is not a file anyone opens
        setFiles((list || []).filter(n => !n.endsWith('/') && !n.startsWith('.') && n.endsWith('.rox')));
        return list || [];
    }

    // Returns the file's text: the caller may want to run it, and React state
    // set here is not readable until the next render, so handing it back is the
    // only way a caller can act on what was just opened.
    async function openFile(ws, name) {
        const monaco = window.monaco;
        // The live editor buffer wins -- it may hold unsaved edits.
        const m = monaco?.editor.getModel(monaco.Uri.parse('inmemory://roxal' + filePath(name)));
        let text = m ? m.getValue() : seed[name];
        if (text === undefined) {
            text = (await ws.call('fs_read', filePath(name))) ?? '';
            setSeed(s => ({ ...s, [name]: text }));
        }
        setTabs(t => (t.includes(name) ? t : [...t, name]));
        setActive(name);
        localStorage.setItem(LAST_FILE_KEY, name);
        return text;
    }

    async function saveFile(ws, name) {
        const ok = await ws.call('fs_write', filePath(name), modelText(name));
        if (ok) setDirtyTabs(d => ({ ...d, [name]: false }));
        return ok;
    }

    // Boot: start a bootstrap script (exposes the workspace), seed /data with
    // the demo on first visit, open the last-used file, then run it.
    useEffect(() => {
        (async () => {
            try {
                const { rox } = await startRoxal(BOOTSTRAP, {
                    expectStore: 'workspace',
                    onOutput: text => { outputRef.current = text; setOutput(text); },
                    hostUrl: hostUrlFromLocation(),
                });
                roxRef.current = rox;
                setRox(rox);
                const ws = rox.roxalStore('workspace');
                // Where this host keeps files (the bootstrap exposed it before
                // the workspace, so the build store is already defined).
                const reported = rox.roxalStore('build').getSnapshot().data_dir;
                if (typeof reported === 'string' && reported) dataDir = reported;

                let list = await refreshFiles(ws);
                let seeded = false;
                // Seeding an example ONCE is not enough: the files live in OPFS
                // and outlive every deploy, so a shipped example that changes
                // never reaches anyone who already has the old copy -- they see
                // a stale demo and no reason why. Update the copies the user has
                // not touched, and never the ones they have: `stamps` records
                // what we last wrote, so "unchanged since we wrote it" is
                // decidable rather than guessed.
                const stamps = readStamps();
                for (const [name, src] of Object.entries(EXAMPLES)) {
                    if (!list.includes(name)) {
                        await ws.call('fs_write', filePath(name), src);
                        stamps[name] = hash(src);
                        seeded = true;
                        continue;
                    }
                    const current = (await ws.call('fs_read', filePath(name))) ?? '';
                    const now = hash(current), shipped = hash(src), stamp = stamps[name];
                    const update = stamp === undefined
                        // No record of writing it: refresh ONLY a copy we
                        // recognise as an older shipment of our own.
                        ? (KNOWN_PRIOR[name] || []).includes(now)
                        // We wrote it: refresh while it is untouched since.
                        : now === stamp && stamp !== shipped;
                    if (update) {
                        await ws.call('fs_write', filePath(name), src);
                        stamps[name] = shipped;
                        disposeModel(filePath(name));   // drop the editor's stale buffer
                        setSeed(s => ({ ...s, [name]: src }));
                        seeded = true;
                    } else if (stamp === undefined) {
                        // Adopt an unrecognised copy: it may be the user's work,
                        // so record it and never touch it. Deliberately NOT done
                        // when a stamp already exists and no longer matches --
                        // that stamp is the proof the user has edited since.
                        stamps[name] = now;
                    }
                }
                writeStamps(stamps);
                if (seeded) list = await refreshFiles(ws);
                const last = localStorage.getItem(LAST_FILE_KEY);
                // ?file=counter4 opens that file instead of the remembered one
                // (or the tanks.rox default) -- a shareable link to a specific
                // example. An unknown name falls back rather than failing to
                // boot, since the URL may outlive the file it names.
                const wanted = requestedFile();
                if (wanted && !list.includes(wanted))
                    console.warn(`?file=${wanted}: not in ${dataDir}, opening the usual file instead`);
                const first = (wanted && list.includes(wanted)) ? wanted
                            : (last && list.includes(last)) ? last : 'tanks.rox';
                await openFile(ws, first);

                const text = await ws.call('fs_read', filePath(first));
                try {
                    // a diagram runs under its full path so its sibling /data
                    // imports (composed sub-diagrams) resolve at boot too
                    await runScript(rox, text ?? '', { expectStore: 'workspace',
                        name: isDiagramSource(text ?? '') ? filePath(first) : first });
                } catch (e) {
                    // A batch example (mnist.rox) as the remembered file: it ran
                    // and finished, which is success, not a boot failure. Its
                    // prints are in the output pane; put the services back.
                    if (!(e.scriptEnded && e.rc === 0)) throw e;
                    await ensureServicesUnarmed();
                }
                setPanel(pickPanel(rox));
                setGeneration(g => g + 1);
            } catch (e) {
                setError(String(e.message || e));
            }
        })();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // One path for "make this file the running program", shared by the Run
    // button and by opening a file. `source` exists because a just-opened file
    // is not yet readable from React state; `save` is false for that case,
    // since the text came off disk unchanged.
    function runNamed(name, opts = {}) {
        const seq = ++runSeqRef.current;            // supersedes any pending run
        const p = runChainRef.current.catch(() => {}).then(() => startRun(name, seq, opts));
        runChainRef.current = p.catch(() => {});
        return p;
    }

    async function startRun(name, seq, { source, save = true, debug = debugOn } = {}) {
        const superseded = () => runSeqRef.current !== seq;
        if (superseded()) return;               // a newer request owns the UI state
        if (!workspace || !name) {              // nothing to run: release the UI
            busyRef.current = false;
            setRunning(false);
            return;
        }
        // A script that loads a model will block the VM inside Model() until
        // the runtime is there; start fetching it now so that wait is short.
        if (rox?.kind === 'wasm' && (source ?? modelText(name)).includes('ai.nn')) warmNnProvider();
        setRunning(true);
        setRunError(null);
        setRunBenign(false);
        busyRef.current = true;
        try {
            // A debug run first RELEASES any active stop: a breakpoint-stopped
            // program cannot answer the displace handshake below.  Only when
            // one is actually held, and never unbounded: a store call to a
            // store nobody services does not fail, it waits out the bridge's
            // 20s timeout -- which is exactly how long the restart then took.
            if (debug && dbgAdapter && dbgStopRef.current) {
                try {
                    await Promise.race([dbgAdapter.resume(),
                                        new Promise(r => setTimeout(r, 2000))]);
                } catch { /* no session */ }
                setDbgStop(null); setDbgInfo(null); dbgStopKeyRef.current = '';
            }
            // Displace whatever owns the VM FIRST (a running batch script
            // never parks, so services could not come back while it runs),
            // then restore services -- Save is a store call and wedges
            // without them.
            await stopCurrent(rox);
            if (superseded()) return;
            await ensureServicesUnarmed();
            if (superseded()) return;
            if (save) await saveFile(workspace, name);        // Run implies Save
            if (superseded()) return;
            let text = source ?? modelText(name);
            if (isDiagramSource(text)) {
                // A diagram file only *defines* its component; running it means
                // running the generated harness -- instantiate, probe the
                // outputs, park in web.serve(). The harness is a string, never
                // a document. Check first: an unconnected port would only fail
                // deep inside wiring with a conversion error.
                const p = filePath(name);
                let opened = await dfCall(df, 'save', p);          // is it open?
                if (!opened.ok && opened.error === 'no_document')
                    opened = await dfCall(df, 'open', p, text);
                if (!opened.ok) throw new Error('diagram: ' + opened.error);
                const chk = await dfCall(df, 'check', p);
                const errs = (chk.ok ? chk.diagnostics : []).filter(d => d.level === 'error');
                if (errs.length)
                    throw new Error('diagram has errors — ' + errs.map(d => d.message).join('; '));
                const h = await dfCall(df, 'harness', p);
                if (!h.ok) throw new Error('diagram harness: ' + h.error);
                text = h.source;
            }
            // diagrams run under their FULL path so sibling /data modules
            // (composed sub-diagrams) resolve on import.  Under a debug
            // session the `debug` store re-exposes at SCRIPT START (before
            // the first user statement), so it is the start signal even for
            // a batch script that will park at a breakpoint.
            if (debug) {
                // Configuration BARRIER (native singletons persist across
                // runs): stop-on-fatal and the breakpoint requests are
                // armed before the source is submitted, so they bind at
                // compile time -- before the first user statement can run,
                // fail, or pass a breakpoint line.
                rox.debugArm(true);
                rox.setBreakpoints(name, bpsRef.current[name] ?? []);
            }
            // expectStore is decided at SUBMIT time from the CURRENT armed
            // state (ref, not closure): if debugging was toggled on while
            // this run's pre-steps were in flight, the run inherits the
            // armed session (its script start exposes the debug store) and
            // must key on that -- watching workspace would time out.
            const debugNow = debug || debugOnRef.current;
            await runScript(rox, text, { expectStore: debugNow ? 'debug' : 'workspace',
                                         assumeStopped: !scriptParked(rox),
                                         name: isDiagramSource(text) ? filePath(name) : name,
                                         superseded });
            setPanel(pickPanel(rox));
            setGeneration(g => g + 1);
        } catch (e) {
            // Displaced by a newer request: it owns the UI state and the
            // services from here on -- saying anything would be a lie about a
            // run the user replaced on purpose.
            if (e && e.superseded) return;
            setRunError(String(e.message || e));
            setRunBenign(Boolean(e.scriptEnded) && e.rc === 0);
            // A script that ended (batch script, or an error before serve) left
            // nothing parked. Put the IDE's own services back so the menus,
            // console and Run keep working.
            try { await ensureServicesUnarmed(); } catch { /* reported above */ }
        } finally {
            // Only the CURRENT run may declare the IDE idle; a superseded one
            // would otherwise blink the button and open a window for the
            // liveness watchdog to re-park under its successor.
            if (!superseded()) {
                busyRef.current = false;
                setRunning(false);
            }
        }
    }

    const rerun = () => runNamed(active);

    // Choosing a script -- from the File menu or its tab -- means "show me this
    // one". Opening without running left the app pane displaying the PREVIOUS
    // script's UI, which reads as the selection not having worked (and a reload
    // then "fixed" it, because boot runs whatever file it reopens).
    async function openAndRun(name) {
        const text = await openFile(workspace, name);
        await runNamed(name, { source: text, save: false });
    }

    // Watchdog for the Run button. Every step of a run is individually bounded
    // (store calls time out, the start/stop loops have deadlines), but they are
    // sequential -- a bad run can chain several timeouts and leave the button
    // reading "running…" long enough to look permanently wedged. Nothing here
    // cancels the work; it just stops the UI from lying about it.
    useEffect(() => {
        if (!running) return;
        const id = setTimeout(() => {
            busyRef.current = false;
            setRunning(false);
            setRunBenign(false);
            setRunError('the run is taking unusually long — the VM may be busy '
                      + '(loading a model runtime, or a script that will not stop). '
                      + 'Press Run again, or reload if it persists.');
        }, 45_000);
        return () => clearTimeout(id);
    }, [running]);

    // A script can also end on its own -- a batch script finishing, or a fatal
    // runtime error minutes later. Poll the liveness invariant and restore the
    // services when it breaks, so the IDE never silently goes dead.
    useEffect(() => {
        if (!rox) return;
        const id = setInterval(async () => {
            if (running || busyRef.current || scriptParked(rox)) return;
            try {
                if (await ensureServicesUnarmed()) setGeneration(g => g + 1);
            } catch { /* next tick tries again */ }
        }, 1000);
        return () => clearInterval(id);
    }, [rox, running]);

    useEffect(() => {
        const onKey = e => {
            if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === 'b') {
                e.preventDefault();
                toggleSource();
            }
        };
        window.addEventListener('keydown', onKey);
        return () => window.removeEventListener('keydown', onKey);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    async function onMenu(action) {
        if (!workspace) return;
        try {
            await ensureServicesUnarmed();
            if (action.kind === 'new') {
                let name = window.prompt('New file name', 'untitled.rox');
                if (!name) return;
                if (!name.endsWith('.rox')) name += '.rox';
                await workspace.call('fs_write', filePath(name), '// ' + name + '\n');
                await refreshFiles(workspace);
                await openFile(workspace, name);
            } else if (action.kind === 'newDiagram') {
                let name = window.prompt('New diagram file name', 'circuit.rox');
                if (!name) return;
                if (!name.endsWith('.rox')) name += '.rox';
                // component type name: PascalCase of the file stem
                const stem = name.slice(0, -4).replace(/[^A-Za-z0-9]/g, ' ');
                const comp = stem.split(' ').filter(Boolean)
                    .map(w => w[0].toUpperCase() + w.slice(1)).join('') || 'Diagram';
                const r = await dfCall(df, 'create', filePath(name), comp,
                                       [{ name: 'freq', default: 4.0 }]);
                if (!r.ok) { setRunError(r.error); return; }
                await workspace.call('fs_write', filePath(name), r.source);
                await refreshFiles(workspace);
                await openFile(workspace, name);
                setSeed(s => ({ ...s, [name]: r.source }));
            } else if (action.kind === 'open') {
                await openAndRun(action.name);
            } else if (action.kind === 'save' && active) {
                await saveFile(workspace, active);
            } else if (action.kind === 'saveAs' && active) {
                let name = window.prompt('Save as', active);
                if (!name) return;
                if (!name.endsWith('.rox')) name += '.rox';
                await workspace.call('fs_write', filePath(name), modelText(active));
                await refreshFiles(workspace);
                await openFile(workspace, name);
            } else if (action.kind === 'reset') {
                if (!window.confirm('Reset the app? This clears ALL stored files, '
                    + 'caches and the service worker for this origin, then reloads.')) return;
                await resetSiteData();
            } else if (action.kind === 'delete' && active) {
                if (!window.confirm('Delete ' + active + '?')) return;
                await workspace.call('fs_delete', filePath(active));
                disposeModel(filePath(active));
                setSeed(({ [active]: _, ...rest }) => rest);
                const remaining = tabs.filter(t => t !== active);
                setTabs(remaining);
                await refreshFiles(workspace);
                if (remaining.length) setActive(remaining[0]);
                else { setActive(null); }
            }
        } catch (e) {
            setRunError(String(e.message || e));
        }
    }

    function closeTab(name) {
        const remaining = tabs.filter(t => t !== name);
        setTabs(remaining);
        if (active === name) setActive(remaining[remaining.length - 1] ?? null);
    }

    // REPL: run the line, return whatever it printed (or the error string).
    //
    // A line can hit a FATAL runtime error (most Roxal runtime errors are, by
    // design) which takes down the whole running app -- and with it the pump
    // that would resolve this very call. So: race a timeout, then check
    // whether the app died and restart it. The fatal message itself arrives
    // on stderr, which is already in the captured output slice.
    async function evalLine(line) {
        if (!workspace || !rox) return '(VM not ready)';
        const before = outputRef.current.length;
        const completedBefore = rox.completedCount();
        let err = '';
        const result = await Promise.race([
            workspace.call('eval', line).catch(e => String(e.message || e)),
            new Promise(r => setTimeout(() => r('__eval_timeout__'), 5000)),
        ]);
        if (result !== '__eval_timeout__') err = result || '';
        // Give the coalesced output flush a beat to land.
        await new Promise(r => setTimeout(r, 60));
        let note = '';
        if (rox.completedCount() > completedBefore) {
            // The line killed the app. Bring it back.
            busyRef.current = true;
            try {
                // The watchdog may already have re-parked the bootstrap; if so
                // this has to stop it first, or the app would queue behind it.
                await runScript(rox, modelText(active),
                                { expectStore: 'workspace', assumeStopped: !scriptParked(rox),
                                  name: active });
                setGeneration(g => g + 1);
                note = '\n(fatal error — app restarted)';
            } catch (e2) {
                // The app itself will not come back (it may not even park).
                // Services still must, or the console dies with it.
                try {
                    await ensureServicesUnarmed();
                    note = '\n(fatal error — app stopped; IDE services restarted)';
                } catch {
                    note = '\n(fatal error — restart failed: ' + String(e2.message || e2) + ')';
                }
            } finally {
                busyRef.current = false;
            }
        } else if (result === '__eval_timeout__') {
            note = '(still running — check the output pane)';
        }
        const printed = outputRef.current.slice(before).replace(/^\[stderr\] /gm, '');
        return (printed + (err || '') + note).trimEnd();
    }

    // The IDE's own bootstrap must never look like a debuggable program:
    // when debugging is on, disarm the session around re-parking it, so its
    // run exposes no debug store (dbgLive then reads the truth).
    // Returns what ensureServices reports: true if it had to re-park the
    // bootstrap, which the liveness watchdog uses to refresh the panel.
    async function ensureServicesUnarmed() {
        const vm = roxRef.current;
        if (!vm) return false;
        if (debugOnRef.current) armDebugSession(vm, false);
        try { return await ensureServices(vm, BOOTSTRAP); }
        finally { if (debugOnRef.current) armDebugSession(vm, true); }
    }

    // Toggling debugging arms/disarms the host session flag.  A program only
    // becomes debuggable when it STARTS under an armed session (the control
    // actor is constructed at script start), so toggling ON restarts the
    // active file -- that is what "debug this" means here.  Toggling OFF
    // releases a live stop so the program cannot be left frozen.
    async function toggleDebug() {
        if (!rox) return;
        const on = !debugOn;
        setDebugOn(on);
        if (!on) {
            // Release any active stop WHILE STILL ARMED (the control natives
            // reject once the session is disarmed), then disarm -- which
            // also tears down debugger policy host-side.  Bounded, and only
            // when something is actually held: an unanswered store call
            // waits out the bridge's 20s timeout, and switching debugging
            // off must never take 20 seconds.
            const held = dbgStopRef.current;
            setDbgStop(null); setDbgInfo(null); setDbgLive(false);
            dbgStopRef.current = null;
            if (held) {
                try {
                    await Promise.race([dbgAdapter?.resume(),
                                        new Promise(r => setTimeout(r, 2000))]);
                } catch { /* not stopped */ }
            }
            armDebugSession(rox, false);
            return;
        }
        armDebugSession(rox, true);
        // Host-level policy armed immediately: even a run already in flight
        // (which then inherits the session) gets stop-on-fatal.
        try { rox.debugArm(true); } catch { /* boot race */ }
        // Unconditional: a run still waiting to start is superseded by this
        // one, and runNamed displaces whatever owns the VM.  Gating on "busy"
        // silently dropped the toggle for exactly the case that needs it --
        // a batch program, whose start-wait runs the full deadline.
        if (active)
            runNamed(active, { debug: true }).catch(() => {});
    }

    function toggleBreakpoint(line) {
        if (!debugOnRef.current || !active) return;
        setBps(prev => {
            const cur = new Set(prev[active] ?? []);
            if (cur.has(line)) cur.delete(line); else cur.add(line);
            const next = { ...prev, [active]: [...cur].sort((a, b) => a - b) };
            bpsRef.current = next;
            // Live edit through the persistent native requests: rebinds the
            // running session AND pre-configures the next run.
            try {
                rox.setBreakpoints(active, next[active]);
            } catch { /* not fatal for the UI */ }
            return next;
        });
    }

    // Stop-state poll: cheap state() calls while debugging; on a NEW stop,
    // fetch the stack + top-frame locals once.
    useEffect(() => {
        if (!debugOn || !dbgAdapter) return;
        let cancelled = false;
        const timer = setInterval(async () => {
            try {
                const st = await dbgAdapter.state();
                if (cancelled) return;
                setDbgLive(true);
                if (st && st.stopped) {
                    setDbgStop(st); dbgStopRef.current = st;
                    const key = `${st.epoch}:${st.thread_id}:${st.line}:${st.reason}`;
                    if (dbgStopKeyRef.current !== key) {
                        dbgStopKeyRef.current = key;
                        const info = await dbgAdapter.describeStop(st);
                        if (cancelled) return;
                        if (info) setDbgInfo(info);
                        else dbgStopKeyRef.current = '';   // transient: retry next poll
                    }
                } else {
                    dbgStopKeyRef.current = '';
                    setDbgStop(null); setDbgInfo(null); dbgStopRef.current = null;
                }
            } catch {
                // Store not alive (no script running yet / just ended).
                if (cancelled) return;
                setDbgStop(null); setDbgInfo(null); setDbgLive(false);
                dbgStopRef.current = null;
                // A debug-run batch script ends DETACHED (runScript returned
                // at start); when nothing is parked any more, put the IDE
                // services back or the console/menus stay dead.
                if (!busyRef.current && rox && !scriptParked(rox)) {
                    busyRef.current = true;
                    try { await ensureServicesUnarmed(); } catch { /* next poll */ }
                    finally { busyRef.current = false; }
                }
            }
        }, 400);
        return () => { cancelled = true; clearInterval(timer); };
    }, [debugOn, dbgAdapter, rox]);

    async function dbgAction(kind) {
        if (!dbgAdapter) return;
        try {
            if (kind === 'pause') await dbgAdapter.pause();
            else if (kind === 'continue') await dbgAdapter.resume();
            else if (dbgStop) await dbgAdapter.step(dbgStop.thread_id, kind);
            // No optimistic clear: the panel is poll-driven, and each stop
            // carries a distinct epoch, so a re-fired breakpoint on the same
            // line still refreshes (clearing here raced the poll, which
            // could re-show the stale stop and swallow the next one).
        } catch { /* surfaces via the poll */ }
    }

    // Browser tests drive the debugger through this handle rather than
    // simulating gutter clicks (the same policy as window.monaco).
    if (typeof window !== 'undefined')
        window.__roxalDebug = { toggleBreakpoint, dbgAction, stop: dbgStop, info: dbgInfo };

    return (
        <main>
            <header>
                <h1>Roxal + React</h1>
                <p className="sub">
                    A Roxal script drives the app — the File menu switches between
                    a <b>signal network</b> (<code>tanks.rox</code>, <code>oven.rox</code>) and
                    a <b>neural net</b> running in this tab (<code>mnist.rox</code>); files persist
                    in the browser's origin-private file system via Roxal's
                    own <code>fileio</code>; the console evaluates through the compiler. React
                    renders it all through <code>useSyncExternalStore</code> and knows nothing else.
                </p>
                {rox && <BuildInfo rox={rox} />}
            </header>

            <div className={'workbench' + (sourceOpen ? '' : ' source-collapsed')}>
                {/* left: the source */}
                <section className="pane editor-pane">
                    <div className="pane-head">
                        <button className="collapse" onClick={toggleSource}
                                title={(sourceOpen ? 'hide' : 'show') + ' the source (Ctrl/⌘-B)'}>
                            {sourceOpen ? '▾' : '▸'} source
                        </button>
                        <FileMenu files={files} onAction={onMenu} />
                        <div className="tabs">
                            {tabs.map(name => (
                                <span key={name}
                                      className={'tab' + (name === active ? ' active' : '')}
                                      onClick={() => { if (name !== active) openAndRun(name); }}>
                                    {name}{dirtyTabs[name] ? ' •' : ''}
                                    {tabs.length > 1 &&
                                        <b className="tab-close"
                                           onClick={e => { e.stopPropagation(); closeTab(name); }}>×</b>}
                                </span>
                            ))}
                        </div>
                        {activeIsDiagram &&
                            <span className="view-toggle">
                                {['diagram', 'source'].map(v => (
                                    <button key={v}
                                            className={'collapse' + (activeView === v ? ' active' : '')}
                                            onClick={() => setViewModes(m => ({ ...m, [active]: v }))}>
                                        {v}
                                    </button>
                                ))}
                            </span>}
                        <button className="run" disabled={!rox || running || !active}
                                onClick={rerun}>{running ? 'running…' : 'Run'}</button>
                        <button className={'debug-toggle' + (debugOn ? ' active' : '')}
                                disabled={!rox}
                                title="Toggle debugging: click the editor gutter to set breakpoints, then Run"
                                onClick={toggleDebug}>{debugOn ? '🐞 debugging' : '🐞'}</button>
                        {runError && <span className={runBenign ? 'run-note' : 'run-error'}>{runError}</span>}
                    </div>
                    {debugOn &&
                        <div className="debug-panel">
                            <span className="debug-status">
                                {dbgStop
                                    ? `⏸ stopped (${dbgStop.reason}) at ${dbgStop.source || '?'}:${dbgStop.line}`
                                    : dbgLive
                                        ? 'running — gutter click sets a breakpoint'
                                        : running
                                            ? 'starting under the debugger…'
                                            : 'no debuggable program — press Run'}
                            </span>
                            <span className="debug-actions">
                                {dbgStop ? <>
                                    <button onClick={() => dbgAction('continue')}>▶ continue</button>
                                    <button onClick={() => dbgAction('next')}>⤵ over</button>
                                    <button onClick={() => dbgAction('in')}>⬇ in</button>
                                    <button onClick={() => dbgAction('out')}>⬆ out</button>
                                </> : <button disabled={!dbgLive}
                                              onClick={() => dbgAction('pause')}>⏸ pause</button>}
                            </span>
                            {dbgStop && dbgInfo &&
                                <div className="debug-detail">
                                    <ul className="debug-stack">
                                        {dbgInfo.frames.slice(0, 6).map(f =>
                                            <li key={f.id}>{f.name} <i>{f.source}:{f.line}</i></li>)}
                                    </ul>
                                    <table className="debug-vars"><tbody>
                                        {dbgInfo.vars.slice(0, 12).map(v =>
                                            <tr key={v.name}>
                                                <td>{v.name}</td><td className="v-type">{v.type}</td>
                                                <td className="v-val">{v.value}</td>
                                            </tr>)}
                                    </tbody></table>
                                </div>}
                        </div>}
                    {active
                        ? (activeView === 'diagram' && df
                            ? <Suspense fallback={<p className="loading">loading the diagram editor…</p>}>
                                  <DfEditor key={active}
                                            path={filePath(active)}
                                            getText={() => modelText(active)}
                                            df={df}
                                            rox={rox}
                                            onOpenFile={n => openFile(workspace, n)}
                                            onSource={src => {
                                                writeModel(active, src);
                                                setDirtyTabs(d => (d[active] ? d : { ...d, [active]: true }));
                                                // Autosave: a graphical edit IS the document; losing
                                                // it to a reload because "Save" was never clicked is
                                                // wrong for a canvas editor.
                                                clearTimeout(autosaveRef.current);
                                                const name = active;
                                                autosaveRef.current = setTimeout(
                                                    () => { saveFile(workspace, name).catch(() => {}); }, 1000);
                                            }} />
                              </Suspense>
                            : <Editor path={filePath(active)}
                                      content={seed[active] ?? ''}
                                      onChange={(path, _text) => {
                                          const name = path.slice(dataDir.length + 1);
                                          setDirtyTabs(d => (d[name] ? d : { ...d, [name]: true }));
                                      }}
                                      service={ide}
                                      breakpoints={debugOn ? (bps[active] ?? []) : null}
                                      stopLine={debugOn && dbgStop
                                                && dbgStop.source === active
                                                ? dbgStop.line : null}
                                      onToggleBreakpoint={debugOn ? toggleBreakpoint : null}
                                      height="100%" />)
                        : <p className="loading">no file open — File → New…</p>}
                </section>

                {/* right: the running app above, output and console below */}
                <div className="right-column">
                    <section className="pane app-pane">
                        <div className="pane-head">
                            <h2>app</h2>
                            {panel === 'tanks' &&
                                <span className="view-toggle">
                                    {tanksView === '3d' &&
                                        <button className={'collapse' + (paused ? ' active' : '')}
                                                title={paused ? 'resume rendering' : 'pause rendering (the app keeps running)'}
                                                onClick={() => setPaused(p => !p)}>
                                            {paused ? '▶' : '⏸'}
                                        </button>}
                                    {['2d', '3d'].map(v => (
                                        <button key={v}
                                                className={'collapse' + (tanksView === v ? ' active' : '')}
                                                onClick={() => pickView(v)}>{v.toUpperCase()}</button>
                                    ))}
                                </span>}
                        </div>
                        <div className="pane-body">
                            {error && <pre className="error">{error}</pre>}
                            {!rox && !error && <p className="loading">starting the Roxal VM…</p>}
                            {rox && panel === 'tanks' && (tanksView === '3d'
                                ? <Suspense fallback={<p className="loading">loading the 3D view…</p>}>
                                      <Tanks3D key={generation} rox={rox} paused={paused} />
                                  </Suspense>
                                : <TanksPanel key={generation} rox={rox} />)}
                            {rox && panel === 'oven' && <OvenPanel key={generation} rox={rox} />}
                            {rox && panel === 'digit' && <MnistPanel key={generation} rox={rox} />}
                            {rox && !panel && !error && activeIsDiagram &&
                                <p className="loading">diagram harness — output probes stream to the
                                    output pane below; live values appear on the canvas edges</p>}
                            {rox && !panel && !error && !activeIsDiagram &&
                                <p className="loading">the running script exposes no known app store</p>}
                        </div>
                    </section>

                    <section className="pane output-pane">
                        <div className="pane-head"><h2>output</h2>
                            <button className="collapse pane-clear" title="clear the output pane"
                                    onClick={() => setOutputClearAt(output.length)}>clear</button>
                        </div>
                        <pre className="pane-body out" ref={outPaneRef}
                             onScroll={e => {
                                 const el = e.currentTarget;
                                 outPinnedRef.current =
                                     el.scrollHeight - el.scrollTop - el.clientHeight < 40;
                             }}>{output.slice(outputClearAt) || '(nothing yet)'}</pre>
                    </section>

                    <section className="pane repl-pane">
                        <div className="pane-head"><h2>console</h2>
                            <button className="collapse pane-clear" title="clear the console log"
                                    onClick={() => setReplGen(g => g + 1)}>clear</button>
                        </div>
                        <Repl key={replGen} evalLine={evalLine} />
                    </section>
                </div>
            </div>
        </main>
    );
}
